name: CC Test Site
favicon: null
layout_spectrum: 0.1836
typography_spectrum: 0.1282597549725324
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
